export { default as Hero } from "./Hero";
export { default as Categories } from "./Categories";
export { default as Collections } from "./Collections";
export { default as Discover } from "./Discover";
export { default as Footer } from "./Footer";
export { default as HIW } from "./HIW";
export { default as Mailing } from "./Mailing";
export { default as TopCreators } from "./TopCreators";
export { default as Exhibition } from "./Exhibition";
